"""
Shared configuration for the Neural Career Advisor.
Updated for Multi-Year (Time-Machine) RAG System.
"""

# --- Data source ---
SURVEY_YEARS = "2021-2025"  # Changed from single year to multi-year range
RAW_RESULTS_FILE = "merged_results.csv"  # The unified dataset generated by NB2
RAW_SCHEMA_FILE = "schema.txt"

# --- Fact generation (Notebook 3) ---
MIN_N = 30  # never generate a fact from fewer respondents than this

# --- Retrieval (Notebooks 4-5, app.py) ---
EMBED_MODEL = "all-MiniLM-L6-v2"
MIN_SCORE = 0.35  # minimum FAISS similarity before a retrieved fact is trusted
TOP_K = 15  # INCREASED: We need more facts to capture trends across 5 different years
MAX_CONTEXT_CHARS = 4500  # INCREASED: Defensive cap expanded for larger historical context

# --- LLM (Notebook 5, app.py) ---
OLLAMA_MODEL = "qwen2.5"

# --- Schema check (Notebook 1) ---
REQUIRED_COLUMNS = [
    "ResponseId", "DevType", "Country", "ConvertedCompYearly", "WorkExp", "YearsCode",
    "EdLevel", "ICorPM", "OrgSize", "RemoteWork", "JobSat", "AISent", "AIThreat",
    "AIAcc", "AIComplex", "AIAgents", "NewRole",
    "LanguageHaveWorkedWith", "DatabaseHaveWorkedWith", "PlatformHaveWorkedWith",
    "WebframeHaveWorkedWith", "AIModelsHaveWorkedWith",
]